name: Create and publish a Docker image

on:
  push:
    tags:
      - '*'
    branches: [ develop ]
env:
  REGISTRY: ghcr.io
  GHCR_IMAGE_NAME: 'meeds-io/meeds/meeds-io'
  DOCKERHUB_IMAGE_NAME: 'meedsio/meeds'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # needed for signing the images with GitHub OIDC Token

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.SWF_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: metaghcr
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.GHCR_IMAGE_NAME }}
          flavor: |
            latest=false

      - name: Build and push Docker image to ghcr.io
        uses: docker/build-push-action@v5
        id: pushghcr
        with:
          context: .
          push: true
          tags: ${{ steps.metaghcr.outputs.tags }}
          labels: ${{ steps.metaghcr.outputs.labels }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: metadockerhub
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKERHUB_IMAGE_NAME }}
          flavor: |
            latest=false

      - name: Build and push Docker image to Dockerhub
        uses: docker/build-push-action@v5
        id: pushdockerhub
        with:
          context: .
          push: true
          tags: ${{ steps.metadockerhub.outputs.tags }}
          labels: ${{ steps.metadockerhub.outputs.labels }}

      - name: Sign the published Dockerhub Docker image with DCT
        uses: sudo-bot/action-docker-sign@latest
        with:
          image-ref: ${{ steps.metadockerhub.outputs.tags }}
          private-key-id: "${{ secrets.DOCKER_PRIVATE_KEY_ID }}"
          private-key: ${{ secrets.DOCKER_PRIVATE_KEY }}
          private-key-passphrase: ${{ secrets.DOCKER_PRIVATE_KEY_PASSPHRASE }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0
        
      - name: Sign the published ghcr.io Docker image with Cosign
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${images}
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          DIGEST: ${{ steps.pushghcr.outputs.digest }}
          TAGS: ${{ steps.metaghcr.outputs.tags }}

      - name: Sign the images with GitHub OIDC Token
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}
        env:
          DIGEST: ${{ steps.pushghcr.outputs.digest }}
          TAGS: ${{ steps.metaghcr.outputs.tags }}

      - name: Sign the published Dockerhub Docker image with Cosign
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${images}
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          DIGEST: ${{ steps.pushdockerhub.outputs.digest }}
          TAGS: ${{ steps.metadockerhub.outputs.tags }}